package com.shaheen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "EmployeeService", targetNamespace = "http://shaheen.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface EmployeeService {


    /**
     * @return returns java.util.List<com.shaheen.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://shaheen.com/", className = "com.shaheen.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://shaheen.com/", className = "com.shaheen.FindAllResponse")
    @Action(input = "http://shaheen.com/EmployeeService/findAllRequest", output = "http://shaheen.com/EmployeeService/findAllResponse")
    public List<Employee> findAll();

    /**
     * @param arg0
     * @return returns com.shaheen.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://shaheen.com/", className = "com.shaheen.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://shaheen.com/", className = "com.shaheen.GetByIdResponse")
    @Action(input = "http://shaheen.com/EmployeeService/getByIdRequest", output = "http://shaheen.com/EmployeeService/getByIdResponse")
    public Employee getById(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * @param arg0
     * @return returns com.shaheen.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://shaheen.com/", className = "com.shaheen.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://shaheen.com/", className = "com.shaheen.UpdateResponse")
    @Action(input = "http://shaheen.com/EmployeeService/updateRequest", output = "http://shaheen.com/EmployeeService/updateResponse")
    public Employee update(
            @WebParam(name = "arg0", targetNamespace = "")
                    Employee arg0);

    /**
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://shaheen.com/", className = "com.shaheen.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://shaheen.com/", className = "com.shaheen.DeleteResponse")
    @Action(input = "http://shaheen.com/EmployeeService/deleteRequest", output = "http://shaheen.com/EmployeeService/deleteResponse")
    public void delete(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * @param arg0
     * @return returns com.shaheen.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://shaheen.com/", className = "com.shaheen.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://shaheen.com/", className = "com.shaheen.InsertResponse")
    @Action(input = "http://shaheen.com/EmployeeService/insertRequest", output = "http://shaheen.com/EmployeeService/insertResponse")
    public Employee insert(
            @WebParam(name = "arg0", targetNamespace = "")
                    Employee arg0);

}
