package com.shaheen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "Calculator", targetNamespace = "http://shaheen.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface Calculator {


    /**
     * @param arg1
     * @param arg0
     * @return returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNumbers", targetNamespace = "http://shaheen.com/", className = "com.shaheen.AddNumbers")
    @ResponseWrapper(localName = "addNumbersResponse", targetNamespace = "http://shaheen.com/", className = "com.shaheen.AddNumbersResponse")
    @Action(input = "http://shaheen.com/Calculator/addNumbersRequest", output = "http://shaheen.com/Calculator/addNumbersResponse")
    public float addNumbers(
            @WebParam(name = "arg0", targetNamespace = "")
                    float arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    float arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subNumbers", targetNamespace = "http://shaheen.com/", className = "com.shaheen.SubNumbers")
    @ResponseWrapper(localName = "subNumbersResponse", targetNamespace = "http://shaheen.com/", className = "com.shaheen.SubNumbersResponse")
    @Action(input = "http://shaheen.com/Calculator/subNumbersRequest", output = "http://shaheen.com/Calculator/subNumbersResponse")
    public float subNumbers(
            @WebParam(name = "arg0", targetNamespace = "")
                    Float arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Float arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divNumbers", targetNamespace = "http://shaheen.com/", className = "com.shaheen.DivNumbers")
    @ResponseWrapper(localName = "divNumbersResponse", targetNamespace = "http://shaheen.com/", className = "com.shaheen.DivNumbersResponse")
    @Action(input = "http://shaheen.com/Calculator/divNumbersRequest", output = "http://shaheen.com/Calculator/divNumbersResponse")
    public float divNumbers(
            @WebParam(name = "arg0", targetNamespace = "")
                    Float arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Float arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mulNumbers", targetNamespace = "http://shaheen.com/", className = "com.shaheen.MulNumbers")
    @ResponseWrapper(localName = "mulNumbersResponse", targetNamespace = "http://shaheen.com/", className = "com.shaheen.MulNumbersResponse")
    @Action(input = "http://shaheen.com/Calculator/mulNumbersRequest", output = "http://shaheen.com/Calculator/mulNumbersResponse")
    public float mulNumbers(
            @WebParam(name = "arg0", targetNamespace = "")
                    Float arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Float arg1);

}
